### ISSUE TITLE
Deactivate Hud in mod menue [to avoid crash in games]

### ISSUE THREAD

**Issue by KabetzuriBoii** [sneakyevil/SleepingDogs-ModMenu#34]
Many have the bug that if they off the hud throught he settings that the game stops working after a few minutes. through this one could avoid the menue and thus not trigger the crash (maybe) . would be cool as an option in general though.

**Comment by sneakyevil** [comment]
I already mentioned it before that there isnt other way to disable HUD besides the in game options which sets global variable to disable hud render which is literally checked inside the main function that begins UI rendering and it prevent it from rendering, if you really having issue with that you might aswell check https://github.com/SDmodding/Script-Mod and use script API to disable hud and you'll see yourself that you gonna have same issue because there isnt any other way to disable HUD.
