### ISSUE TITLE
Sleeping dogs audio files access

### ISSUE THREAD

**Issue by KabetzuriBoii** [sneakyevil/SleepingDogs-ModMenu#49]
I wanted to ask how to extract audio files . if its not too much of a task for you to explain how ... for a coding noob like me haha xD . thx in advance for everything you do

**Comment by VertofChest** [comment]
I tried, I use BIG Extractor :D

**Comment by KabetzuriBoii** [comment]
> I tried, I use BIG Extractor :D

OH IMMA TRY IT RIGHT NOW ! haha xD D;

**Comment by sneakyevil** [comment]
You can use `Ravioli Game Tools` to extract the .pck files, here is link https://www.scampers.org/steve/sms/other.htm (But not sure if it's correct one). All sounds will be mostly hashed. Sound files contain some names in header so you can build my one program that I wrote to rename all those files: https://github.com/SDmodding/WemNameGrabber for SFX you can manually browse this: https://github.com/SDmodding/Files/blob/main/AudioSFX.xml there id's for file and even original names. Also I'm closing this because this is unrelated to Mod Menu.

**Comment by KabetzuriBoii** [comment]
my gawd . this is like asmr . it sounds way better than in the game haha xD
